### ISSUE TITLE
Deployment issues with S3 Bucket settings

### ISSUE THREAD

**Issue by lvpcguru** [dan335/dominus#18] opened 2019-04-10 14:18 UTC
Meteor deployment fails due to hard coded bucket and region settings used in Mapbaker. The bucket name cant be used more than once. These might be better deployed as an environment variable for easier integration with non dominusgame.net installations.

**Comment by lvpcguru** [comment] 2019-04-10 14:48
It is in the settings.json and could be added to the readme as a build option using this 

> --mobile-settings=settings.json

Without updating the mapbaker I managed an easy work around to include the JSON in an env variable like this: 

> METEOR_SETTINGS='{"public": {"s3": {"region": "<yourregion>","bucket": "<yourbucketname>","url": "<yoururl>","bakePath": "bakes/","avatarPath": "avatars/","serveBakesFromS3": false }  }}'

**Comment by dan335** [comment] 2019-04-10 20:11
settings.json is an example.  You should be creating your own settings.json and filling in the values.

Use --settings settings.json not "mobile-settings"

Info about settings.json https://docs.meteor.com/api/core.html#Meteor-settings

Closing this because it's working as intended.  If you want to chat find me on Discord.

**Closed as completed by dan335** 2019-04-10 20:11 UTC
